name: 'SmartBugs Static Analysis'
description: 'Run SmartBugs static analysis tools on Solidity Contracts in repo. Tools available: Honeybadger, Maian, Manticore, Mythril, Osiris, Oyente, Securify, Slither, SmartCheck, Solhint.'
inputs:
  tool:
    description: 'Specify tools to run the analysis. By default mythril and slither are run. Example: "oyente mythril maian".'
    required: false
    default: 'mythril slither'
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v2.3.4
  - name: "Run python"
    shell: bash
    run: python3 ${{ github.action_path }}/upload.py --tool ${{ inputs.tool }} --token ${{ github.sha }}
  - name: Upload SARIF file
    uses: github/codeql-action/upload-sarif@v1
    with:
        sarif_file: smartbugs/results/results.sarif
